name: Deploy DE

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  set_release:
    runs-on: ubuntu-latest
    environment: 'DE Prod'
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run:
          gh variable set CURRENT_RELEASE -b ${{ github.ref_name }}

